version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/home/deep/resnet
    #  - ./dev/.ssh:/root/.ssh
    #command: bash -c ""